
CREATE TABLE IF NOT EXISTS BAIA (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Tamanho DOUBLE NOT NULL,
  Limpeza BOOLEAN,
);

CREATE TABLE IF NOT EXISTS SUINO (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL, 
    DataNascimento DATE NOT NULL, 
    DataAquisicao DATE NOT NULL,
);

/*CREATE TABLE IF NOT EXISTS PORCOBAIA (
  BAIA_id INTEGER NOT NULL,
  SUINO_id INTEGER NOT NULL,
  PRIMARY KEY(BAIA_id, SUINO_id),
);

ALTER TABLE PORCOBAIA ADD CONSTRAINT IF NOT EXISTS FK_PORCOBAIA _PORCO FOREIGN KEY( SUINO_id) REFERENCES SUINO(id);

ALTER TABLE PORCOBAIA ADD CONSTRAINT IF NOT EXISTS FK_PORCOBAIA _BAIA FOREIGN KEY( BAIA_id) REFERENCES BAIA(id);*/