
CREATE TABLE IF NOT EXISTS BAIA (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Tamanho DOUBLE NOT NULL,
  Limpeza BOOLEAN,
);

CREATE TABLE IF NOT EXISTS SUINO (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(50) NOT NULL, 
    DataNascimento DATE NOT NULL, 
    DataAquisicao DATE NOT NULL,
);

/*CREATE TABLE PORCOBAIA (
  BAIA_id INTEGER NOT NULL,
  SUINO_id INTEGER NOT NULL,
  PRIMARY KEY(BAIA_id, SUINO_id),
  INDEX PORCOBAIA_FKIndex1(BAIA_id),
  INDEX PORCOBAIA_FKIndex2(SUINO_id)
);*/